project:
  type: website
  output-dir: docs

website:
  title: "alex_dspg_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/alexcory1
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

editor: visual

