---
title: "Week One Blog"
author: "Alex Cory"
dat: "2023-05-23"
category: "Week One"
---

# Test

```{r, warning=FALSE, include=FALSE}
library(tidycensus)
library(tidyverse)
```

```{r include=FALSE}
langList_noEng = c("Spanish" = "C16001_003",   "French, Haitian, or Cajun" = "C16001_006",   "German or other West Germanic languages" = "C16001_009",   "Russian, Polish, or other Slavic languages" = "C16001_012",   "Other Indo-European languages" = "C16001_015",   "Korean" = "C16001_018",   "Chinese (incl. Mandarin, Cantonese)" = "C16001_021",   "Vietnamese" = "C16001_024",   "Tagalog (incl. Filipino)" = "C16001_027",   "Other Asian and Pacific Island languages" = "C16001_030",   "Arabic" = "C16001_033",   "Other and unspecified languages" = "C16001_036" )


iowa_lang <- get_acs(
  state = "IA",
  geography = "county",
  variables = langList_noEng,
  geometry = TRUE,
)

```
```{r}
lang_map <- iowa_lang %>%
  ggplot(aes(fill = log(estimate))) + 
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank()  #remove y axis ticks
        ) +
  geom_sf(color = NA) + 
  facet_wrap(~variable) +
  scale_fill_viridis_c(option = "E") 
```
