---
title: "Week Two Blog"
author: "Alex Cory"
dat: "2023-05-23"
category: "Week Two"
---

# Map of languages spoken in Iowa, by language

```{r, warning=FALSE, include=FALSE}
library(tidycensus)
library(tidyverse)
library(dplyr)
```

```{r include=FALSE}
langList_noEng = c("Spanish" = "C16001_003",   "French" = "C16001_006",   "German" = "C16001_009",   "Slavic languages" = "C16001_012",   "Other Indo-European" = "C16001_015",   "Korean" = "C16001_018",   "Chinese " = "C16001_021",   "Vietnamese" = "C16001_024",   "Tagalog" = "C16001_027",   "Asian/Pacific Island" = "C16001_030",   "Arabic" = "C16001_033",   "Other" = "C16001_036" )


iowa_lang <- get_acs(
  state = "IA",
  geography = "county",
  variables = langList_noEng,
  geometry = TRUE,
)

```
```{r}
lang_map <- iowa_lang %>%
  ggplot(aes(fill = log(estimate))) + 
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank()  #remove y axis ticks
        ) +
    labs(title = "Languages by County in Iowa") +
  geom_sf(color = NA) + 
  facet_wrap(~variable) +
  scale_fill_viridis_c(option = "E") 
lang_map
```

```{r, include=FALSE}
iowa_income <- get_acs(
  state = "IA",
  geography = "tract",
  variables = "B06011_001",
  geometry = TRUE,
)
```
```{r}
iowa_income %>%
  ggplot(aes(fill = estimate)) + 
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank()  #remove y axis ticks
        ) +
  labs(title = "Income by Tract") +
  geom_sf(color = NA) + 
  facet_wrap(~variable) +
  scale_fill_viridis_c(option = "E") 
```
# Mean Age by County
```{r, include=FALSE}
age_by_gender = c("Female"="B01002_003","Male"="B01002_002", "Both"="B01002_001")

iowa_ages_by_gender <- get_acs(
  state = "IA",
  geography = "county",
  variables = age_by_gender,
  geometry = TRUE,
)
```

```{r}
iowa_ages_by_gender %>%
  ggplot(aes(fill = estimate)) + 
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank()  #remove y axis ticks
        ) +
  labs(title = "Average Age by County") +
  geom_sf(color = NA) + 
  facet_wrap(~variable) +
  scale_fill_viridis_c(option = "E") 
```

```{r, include=FALSE}
iowa_ages_by_gender <- get_acs(
  state = "IA",
  geography = "tract",
  variables = "B01002_001",
  geometry = TRUE,
)
```
```{r}
iowa_ages_by_gender %>%
  ggplot(aes(fill = estimate)) + 
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        axis.text.y=element_blank(),  #remove y axis labels
        axis.ticks.y=element_blank()  #remove y axis ticks
        ) +
  labs(title = "Average Age by Tract (Male and Female)") +
  geom_sf(color = NA) + 
  facet_wrap(~variable) +
  scale_fill_viridis_c(option = "E") 
```
